/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionnairenote;

/**
 *
 * @author EA2i-03
 */
public class ChargementPage extends javax.swing.JFrame {

    /**
     * Creates new form ChargementPage
     */
    public ChargementPage() {
        initComponents();
       jLabelPoint.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jLabelTitre = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabelPoint = new javax.swing.JLabel();
        FondChargement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnairenote/Icons/GoEtudiantsRase.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 410, 240));

        jLabelNote.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabelNote.setForeground(new java.awt.Color(67, 70, 81));
        jLabelNote.setText("100");
        getContentPane().add(jLabelNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 40, 20));

        jLabelTitre.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTitre.setText("Préparation du programme");
        getContentPane().add(jLabelTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(18, 117, 209));
        jProgressBar1.setBorder(null);
        jProgressBar1.setBorderPainted(false);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 328, 400, 3));

        jLabelPoint.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelPoint.setForeground(new java.awt.Color(18, 117, 209));
        jLabelPoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPoint.setText(".");
        jLabelPoint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 20, 20));

        FondChargement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionnairenote/Icons/GoEtudiants.png"))); // NOI18N
        getContentPane().add(FondChargement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChargementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChargementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChargementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChargementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChargementPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondChargement;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelNote;
    public static javax.swing.JLabel jLabelPoint;
    public static javax.swing.JLabel jLabelTitre;
    public static javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
